# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.29
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 17.0
org_name: Gusti Tammam
org_slug: gustitammam
rebel_module_groups: []
repo_description: Odoo modules by Gusti Tammam
repo_name: Odoo Addons
repo_slug: odoo-addons
repo_website: https://github.com/gustitammam/odoo-addons
use_pyproject_toml: true
use_ruff: true

